---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- ../../../deploy
# - cluster-two-peering.yaml
labels:
- includeSelectors: true
  pairs:
    k8s-app: webmesh-cni
patches:
- patch: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: webmesh-config
      namespace: kube-system
    data:
      cluster-domain: "cluster-one.local"
      pod-cidr: "10.42.0.0/16,fd00:10:42::/48"
      service-cidr: "10.96.0.0/12,fd00:10:96::/112"
