apiVersion: v1
kind: Pod
metadata:
  name: debug-box
  namespace: kube-system
spec:
  containers:
    - name: debug
      image: ghcr.io/webmeshproj/webmesh-cni:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: true
