apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- ./bundle.yaml
labels:
- includeSelectors: true
  pairs:
    k8s-app: webmesh-cni
images:
- name: ghcr.io/webmeshproj/webmesh-cni
  newName: ghcr.io/webmeshproj/webmesh-cni
  newTag: latest
