# This is a Kind cluster configuration with the Webmesh 
# gRPC API and the cni-node WireGuard ports exposed to
# the host.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: webmesh-cni
networking:
  ipFamily: dual
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
  podSubnet: "10.42.0.0/16"
  serviceSubnet: "10.96.0.0/12,fd00:10:96::/112"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/net/tun
    containerPath: /dev/net/tun
  - hostPath: /dev/shm
    containerPath: /dev/shm
  extraPortMappings:
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
  - containerPort: 61820
    hostPort: 61820
    protocol: UDP
