kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-cluster-two
networking:
  ipFamily: dual
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
  podSubnet: "10.43.0.0/16,fd00:10:43::/48"
  serviceSubnet: "10.97.0.0/12,fd00:10:97::/112"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/net/tun
    containerPath: /dev/net/tun
  extraPortMappings:
  - containerPort: 8443
    hostPort: 8444
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    networking:
      dnsDomain: "cluster-two.local"
