kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-cluster-one
networking:
  ipFamily: dual
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
  podSubnet: "10.42.0.0/16,fd00:10:42::/48"
  serviceSubnet: "10.96.0.0/12,fd00:10:96::/112"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/net/tun
    containerPath: /dev/net/tun
  extraPortMappings:
  - containerPort: 8443
    hostPort: 8441
    protocol: TCP
  - containerPort: 53
    hostPort: 5351
    protocol: UDP
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    networking:
      dnsDomain: "cluster-one.local"
