---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webmesh-cni-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cni.webmesh.io
  resources:
  - peercontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cni.webmesh.io
  resources:
  - peercontainers/finalizers
  verbs:
  - update
- apiGroups:
  - cni.webmesh.io
  resources:
  - peercontainers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cni.webmesh.io
  resources:
  - remotenetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cni.webmesh.io
  resources:
  - remotenetworks/finalizers
  verbs:
  - update
- apiGroups:
  - cni.webmesh.io
  resources:
  - remotenetworks/status
  verbs:
  - get
  - patch
  - update
