---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webmesh-cni-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webmesh-cni-role
subjects:
  - kind: ServiceAccount
    name: webmesh-cni-sa
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webmesh-cni-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webmesh-storage-role
subjects:
  - kind: ServiceAccount
    name: webmesh-cni-sa
    namespace: kube-system
