manager:
  image:
    repository: ghcr.io/webmeshproj/vdi-manager
    tag: latest
vdi:
  spec:
    app:
      image: ghcr.io/webmeshproj/vdi-app:latest
      serviceType: ClusterIP
    auth:
      tokenDuration: 8h
      oidcAuth:
        issuerURL: http://169.254.169.254
        redirectURL: https://kvdi.default.svc.cluster.local/api/login
