---
apiVersion: v1
kind: Namespace
metadata:
  name: vdi
---
apiVersion: app.kvdi.io/v1
kind: VDICluster
metadata:
  name: desktops
spec:
  appNamespace: vdi
  app:
    image: ghcr.io/webmeshproj/vdi-app:latest
    replicas: 1
    serviceName: desktops
    serviceType: ClusterIP
    tls:
      disable: true
  auth:
    adminSecret: kvdi-admin-secret
    allowAnonymous: false
    webmeshAuth:
      metadataURL: http://169.254.169.254
    tokenDuration: 8h
  desktops:
    maxSessionLength: 8h
  secrets:
    k8sSecret:
      secretName: kvdi-app-secrets
  userdataSpec: {}
