# The VDI deployment
---
apiVersion: v1
kind: Namespace
metadata:
  name: vdi
---
apiVersion: app.kvdi.io/v1
kind: VDICluster
metadata:
  name: desktops
spec:
  appNamespace: vdi
  app:
    image: ghcr.io/webmeshproj/vdi-app:latest
    replicas: 1
    serviceName: desktops
    serviceType: ClusterIP
    tls:
      disable: true
  auth:
    adminSecret: kvdi-admin-secret
    allowAnonymous: false
    webmeshAuth:
      metadataURL: http://169.254.169.254
    tokenDuration: 8h
  desktops:
    maxSessionLength: 8h
  secrets:
    k8sSecret:
      secretName: kvdi-app-secrets
  userdataSpec: {}
---
# An admin role for people in the "desktop-admins" webmesh group.
apiVersion: rbac.kvdi.io/v1
kind: VDIRole
metadata:
  name: webmesh-desktop-admin
  annotations:
    kvdi.io/webmesh-groups: desktop-admins
  labels:
    kvdi.io/cluster-ref: desktops
rules:
- namespaces:
  - '*'
  resourcePatterns:
  - .*
  resources:
  - '*'
  verbs:
  - '*'
---
# Desktop templates
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  desktop:
    image: ghcr.io/webmeshproj/desktop-ubuntu-base-xfce4:latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    image: ghcr.io/webmeshproj/vdi-proxy:latest
    allowFileTransfer: true
  tags:
    os: ubuntu
    desktop: xfce4
---
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-kde
spec:
  desktop:
    image: ghcr.io/webmeshproj/desktop-ubuntu-base-kde:latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    image: ghcr.io/webmeshproj/vdi-proxy:latest
    allowFileTransfer: true
  tags:
    os: ubuntu
    desktop: kde
