---
apiVersion: v1
kind: Namespace
metadata:
  name: desktops
---
apiVersion: app.kvdi.io/v1
kind: VDICluster
metadata:
  name: vdi
spec:
  appNamespace: desktops
  app:
    image: "ghcr.io/webmeshproj/vdi-app:latest"
    replicas: 1
    serviceType: ClusterIP
  auth:
    adminSecret: kvdi-admin-secret
    allowAnonymous: false
    webmeshAuth:
      metadataURL: http://169.254.169.254
    tokenDuration: 8h
  desktops:
    maxSessionLength: 8h
  secrets:
    k8sSecret:
      secretName: kvdi-app-secrets
  userdataSpec: {}
