kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: webmesh-cni
networking:
  ipFamily: dual
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
  podSubnet: "10.42.0.0/16,fd00:10:42::/48"
  serviceSubnet: "10.96.0.0/16,fd00:10:96::/112"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev/net/tun
    containerPath: /dev/net/tun
- role: worker
  extraMounts:
  - hostPath: /dev/net/tun
    containerPath: /dev/net/tun
